stk_finance:
    resource: "@StkFinanceBundle/Resources/config/routing.yml"
    prefix:   /finance

stk_adhesion:
    resource: "@StkAdhesionBundle/Resources/config/routing.yml"
    prefix:   /adhesion

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
