<?php

namespace Stk\AdhesionBundle\Repository;

/**
 * MembreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembreRepository extends \Doctrine\ORM\EntityRepository
{
    public function findChoralMembre() {
        $query = $this->createQueryBuilder('membre')
            ->where('membre.status like :status')->setParameter('status','c');
        return $query->getQuery()->getResult();
    }
    
    public function findChoralBC() {
        $query = $this->createQueryBuilder('membre')
            ->where('membre.likeAs like :likeAs')->setParameter('likeAs','b')
            ->orWhere('membre.likeAs like :likeAs')->setParameter('likeAs','c');
        return $query->getQuery()->getResult();
    }

    public function getMaxId() {
        $query = $this->createQueryBuilder('membre')
            ->select('MAX(membre.id)');
        return $query->getQuery()->getSingleScalarResult();
    }
}
