<?php

namespace Stk\AdhesionBundle\Repository;
use Stk\AdhesionBundle\Entity\Membre;

/**
 * PresenceBCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresenceBCRepository extends \Doctrine\ORM\EntityRepository
{
    public function countPresenceBy(Membre $membre, $annee) {
        $query = $this->createQueryBuilder('presence')
            ->select('count(presence.id)')
            ->where('YEAR(presence.date) = :year')->setParameter('year', $annee)
            ->andWhere('presence.membre = :membre')->setParameter('membre', $membre);
        return $query->getQuery()->getOneOrNullResult();
    }
}
