<?php

namespace Stk\AdhesionBundle\Repository;
use DoctrineExtensions\Query\Mysql\Date;
use Stk\AdhesionBundle\Entity\Membre;

/**
 * PresenceBCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PresenceBCRepository extends \Doctrine\ORM\EntityRepository
{
    public function countPresenceBy(Membre $membre, $annee) {
        $query = $this->createQueryBuilder('presence')
            ->select('count(presence.id)')
            ->where('YEAR(presence.date) = :year')->setParameter('year', $annee)
            ->andWhere('presence.membre = :membre')->setParameter('membre', $membre);
        return $query->getQuery()->getOneOrNullResult();
    }

    public function isExist(Membre $membre, $date) {
        ///
        $query = $this->createQueryBuilder('presence')
            ->where('YEAR(presence.date) = :date')->setParameter('date', date('Y',$date->getTimestamp()))
            ->andWhere('MONTH(presence.date) = :date')->setParameter('date', date('M',$date->getTimestamp()))
            ->andWhere('presence.membre = :membre')->setParameter('membre', $membre);
        return $query->getQuery()->getResult() != null;
    }
}
